apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kimai
  name: kimai
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kimai
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: kimai
    spec:
      containers:
        - env:
            - name: ADMINMAIL
              value: admin@kimai.local
            - name: ADMINPASS
              value: changemeplease
            - name: DATABASE_URL
              value: mysql://kimaiuser:kimaipassword@sqldb/kimai
            - name: TRUSTED_HOSTS
              value: nginx,localhost,127.0.0.1
          image: kimai/kimai2:fpm
          name: kimai
          resources: {}
          volumeMounts:
            - mountPath: /opt/kimai/public
              name: public
      restartPolicy: Always
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: public
status: {}
