apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: tobybatch/nginx-fpm-reverse-proxy
          livenessProbe:
            exec:
              command:
                - wget --spider http://nginx/health || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /opt/kimai/public
              name: public
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: public
            readOnly: true
status: {}
